blank_issues_enabled: false
contact_links:
  - name: "Preguntas Frecuentes y Soporte"
    url: "https://github.com/jugpanama/governance/discussions"
    about: "Si tu duda no requiere un reporte formal o una propuesta, utiliza el foro de discusión de la comunidad."
